import { NextRequest, NextResponse } from 'next/server';
import { getGeminiServerClient, isGeminiConfigured } from '@/lib/ai/gemini-server';

export async function POST(req: NextRequest) {
  try {
    if (!isGeminiConfigured()) {
      return NextResponse.json(
        { error: 'Gemini API key is not configured. Please configure GEMINI_API_KEY in your environment.' },
        { status: 503 }
      );
    }

    const { prompt, aspectRatio = '1:1', style = 'photorealistic' } = await req.json();

    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json({ error: 'A valid text prompt is required.' }, { status: 400 });
    }

    const ai = getGeminiServerClient();

    // Enhance prompt with style modifiers
    let enhancedPrompt = prompt.trim();
    if (style === 'photorealistic') {
      enhancedPrompt += ', highly detailed, 8k resolution, photorealistic, professional lighting, cinematic composition';
    } else if (style === 'cyberpunk') {
      enhancedPrompt += ', cyberpunk aesthetic, neon lights, volumetric glow, futuristic octane render';
    } else if (style === '3d-render') {
      enhancedPrompt += ', 3D isometric render, Blender 3D, smooth materials, studio ambient occlusion';
    } else if (style === 'minimalist') {
      enhancedPrompt += ', minimalist vector art, clean lines, elegant modern design, balanced palette';
    } else if (style === 'watercolor') {
      enhancedPrompt += ', artisanal watercolor painting, soft pigment washes, textured paper, subtle splashes';
    }

    // Supported aspect ratios: "1:1", "3:4", "4:3", "9:16", "16:9"
    const validRatios = ['1:1', '3:4', '4:3', '9:16', '16:9'];
    const chosenRatio = validRatios.includes(aspectRatio) ? aspectRatio : '1:1';

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-lite-image',
      contents: {
        parts: [{ text: enhancedPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: chosenRatio as '1:1' | '3:4' | '4:3' | '9:16' | '16:9',
        },
      },
    });

    const candidate = response.candidates?.[0];
    const parts = candidate?.content?.parts || [];

    let imageBase64: string | null = null;
    let mimeType = 'image/png';
    let textDescription = '';

    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        imageBase64 = part.inlineData.data;
        if (part.inlineData.mimeType) {
          mimeType = part.inlineData.mimeType;
        }
        break;
      } else if (part.text) {
        textDescription += part.text;
      }
    }

    if (!imageBase64) {
      return NextResponse.json(
        {
          error: 'No image data was generated by the model. The model returned: ' + (textDescription || 'empty response'),
        },
        { status: 502 }
      );
    }

    return NextResponse.json({
      imageUrl: `data:${mimeType};base64,${imageBase64}`,
      prompt: enhancedPrompt,
      originalPrompt: prompt,
      aspectRatio: chosenRatio,
      style,
      timestamp: Date.now(),
    });
  } catch (error: unknown) {
    console.error('Image Generation API Error:', error);
    const message = error instanceof Error ? error.message : 'Image generation failed';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
